### PR TITLE
Resolve Faker generator via application service container

### PR DESCRIPTION
**Pull request by maartenpaauw**
In an application (where we make use of this package) we have a custom Faker provider. I a service provider we add the custom provider so we can make use of it in our database factories:

```php
// ...

$this->app->afterResolving(Generator::class, static function (Generator $generator): void {
    $generator->addProvider(new CustomProvider($generator));
});

// ...
```

With the changes in this pull request I can use the same custom Faker provider methods inside the definition array.

```php
// ...

public function definition(): array
{
    return [
        'foo' => $this->faker()->customMethod,
    ];
}

// ...
```

I had to move the `RequestFactoryTest` class inside the `Feature` namespace because a Laravel's container is needed for resolving a `Generator` instance.

### CODE REVIEW

**Review by RazorMeister — APPROVED** [review]
Very good idea!

**Review by olivernybroe — COMMENTED** [review]
Nice, I think this makes sense to do. 

Would love if we could do this with dependency injection instead, however on top of my head I can't really see it easily. 🤔

**Review by olivernybroe — CHANGES_REQUESTED** [review]
We came up with an idea of how to get the faker from the container, while not using the container for resolving it, so factories does not depend on it.


Essentially we first need the faker once the result is being generated, so we can lazy initialise the faker variable instead by having a setter for the faker variable which will be set inside of `\Worksome\RequestFactories\Actions\CreateFactoryResult`. 

This class can then get the faker instance by dependency injection.

@lukeraymonddowning do you approve of this approach?

**Comment by lukeraymonddowning** [comment]
@olivernybroe thinking more on our idea I've realised it won't really work in all cases. For example, helper methods, which are invoked before the factory will have been set.

```php
UploadRequest::withRandomName()->create();

public function withRandomName()
{
  // Whoops, this will blow up!
  return $this->state(['name' => $this->faker->name]);
}
```

**Comment by olivernybroe** [comment]
@lukeraymonddowning ah right... Hmm, could maybe work if we wrap the request factory in a lazy class. 
E.g. a class the registers all the method calls, but first calls them at the end 👀

**Comment by lukeraymonddowning** [comment]
Thinking on it, this is possible in user-land by extending the abstract class and overriding `configure`, then setting `$faker` using `app()` as outlined here.

**Comment by lukeraymonddowning** [comment]
> @lukeraymonddowning ah right... Hmm, could maybe work if we wrap the request factory in a lazy class.
> E.g. a class the registers all the method calls, but first calls them at the end 👀

@olivernybroe seems like a lot of edge-case effort for a tiny change.

**Comment by lukeraymonddowning** [comment]
@maartenpaauw going to opt for #21 just to avoid needing to reference the container in the constructor. Feels a little like I'm gatekeeping on this one but we try to avoid reaching for service location as much as possible. Really appreciate you opening this PR ❤️

**Comment by maartenpaauw** [comment]
> @maartenpaauw going to opt for #21 just to avoid needing to reference the container in the constructor. Feels a little like I'm gatekeeping on this one but we try to avoid reaching for service location as much as possible. Really appreciate you opening this PR ❤️

No worries! I'm glad this feature is added.

**Pull request closed without merging**
