### PR TITLE
Adds dot-notation support for the `state` method.

### PR DESCRIPTION
**Pull request by lukeraymonddowning**
Based on discussion #9, this PR allows a user to set a deeply nested array value using the `state` method.

```php
$data = MyRequestFactory::new()->state(['address.line_one' => '1 Test Street'])->create();
```

@dcaswel can you please verify that this solves your use case?

### CODE REVIEW

**Comment by dcaswel** [comment]
Yeah, I think this would do the trick. Thanks!

**Review by olivernybroe — APPROVED** [review]
I am fine with this, think it makes a lot of sense in the Laravel world 🙂 however my biggest concern here is what do we do if people has request params with dots in them? 

Is that just unsupported now 👀

**Comment by lukeraymonddowning** [comment]
I wonder if we should support escaping dots with '\' or if that's just over engineering?

**Comment by olivernybroe** [comment]
@lukeraymonddowning after your poll I would say let's add escaping support 👍 
We have to be aware that this will be a BC.

**Comment by lukeraymonddowning** [comment]
@olivernybroe this is ready for a re-review. I've added support for escaping using the \ character. Wondering if there are any other changes we should bundle in with 2.x?

**Review by olivernybroe — APPROVED** [review]
Just became a lot bigger 😆 
But really nice, seems like you are using the same "hack" as laravel requests are doing with a placeholder

**Comment by lukeraymonddowning** [comment]
> Just became a lot bigger 😆
> But really nice, seems like you are using the same "hack" as laravel requests are doing with a placeholder

Indeed, `Str::random()` FTW!

**Pull request merged**
